### ISSUE TITLE
获取验证结果中的一个问题

### ISSUE THREAD

**Issue by sco4x0** [jormin/laravel-geetest#2]
在`GeetestLib`的`successValidate`方法里，接收的参数`$param`是`session->get('user_id')`，这里获取到的user_id是一个`string`，不做一下处理的话array_merge会报错

官方给的demo中也是对这个地方做了处理的
```php
if (($user_id != null) and (is_string($user_id))) {
        $query["user_id"] = $user_id;
    }
```

**Comment by jormin** [comment]
v1.0.1已经修改了这个错误，感谢指正🙏
